"""
Abstract base class for memory management strategies.
All memory modes must inherit from this class.

Includes hybrid memory support:
- **Sliding window**: subclasses keep last N messages verbatim
- **Incremental summary**: older messages are summarised by the LLM
- **Vector recall** (optional): evicted messages are embedded for
  semantic retrieval, improving long-term awareness
"""

import json
import logging
from abc import ABC, abstractmethod
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from src.memory.base import BaseMemoryStore
from src.memory.context import MemoryContext

# Optional LangChain types — imported lazily in helpers
try:
    from langchain_core.messages import AIMessage, BaseMessage, HumanMessage
except ImportError:  # pragma: no cover
    BaseMessage = None  # type: ignore[misc, assignment]
    HumanMessage = None  # type: ignore[misc, assignment]
    AIMessage = None  # type: ignore[misc, assignment]

log = logging.getLogger("cogtrix")

# Summarize when at least this many messages have fallen out of the
# sliding window since the last summary was generated.
_SUMMARY_BATCH_SIZE = 6

# Error prefixes that should never be stored in conversation history.
# These are generated by _format_agent_error() in cogtrix.py.
_ERROR_PREFIXES = (
    "**Model not found:**",
    "**Authentication failed:**",
    "**Rate limit exceeded.**",
    "**Connection error:**",
    "**Request timed out.**",
    "**Prompt too long",
    "**Invalid request:**",
    "**API server error",
    "**Service temporarily unavailable",
    "**Error:**",
    "**Agent iteration limit reached.**",
    "**Partial results",
)


def _coerce_content(content: Any) -> str:
    """Safely coerce message content to a plain string.

    LangChain messages may carry ``content`` as a ``str``, a ``list``
    (multimodal messages), or occasionally ``None``.  This helper
    normalises all variants to a flat string so downstream code can
    safely call ``.strip()`` etc.
    """
    if isinstance(content, str):
        return content
    if content is None:
        return ""
    if isinstance(content, list):
        parts: list[str] = []
        for item in content:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict):
                parts.append(item.get("text", str(item)))
            else:
                parts.append(str(item))
        return " ".join(parts)
    return str(content)


def _is_bad_ai_content(content: Any) -> bool:
    """Check if AI message content is empty or an error message.

    Accepts any content type (str, list, None) and coerces to string
    before checking.
    """
    text = _coerce_content(content)
    if not text or not text.strip():
        return True
    stripped = text.strip()
    for prefix in _ERROR_PREFIXES:
        if stripped.startswith(prefix):
            return True
    return False


class BaseMemoryManager(ABC):
    """
    Abstract interface for memory management strategies.

    Each memory mode (conversation, code, reasoning) implements this
    interface to provide mode-specific context preparation and updates.

    Lifecycle:
        1. __init__() - Create manager with store and session
        2. load() - Load existing state from storage
        3. prepare_context() - Get context for LLM (called before each turn)
        4. update() - Update memory after LLM response
        5. save() - Persist state to storage

    Attributes:
        store: Storage backend for persistence
        session_id: Unique identifier for this session
        config: Mode-specific configuration options
    """

    def __init__(
        self,
        store: BaseMemoryStore,
        session_id: str,
        config: dict[str, Any] | None = None,
    ):
        """
        Initialize the memory manager.

        Args:
            store: Storage backend (e.g., JsonFileMemoryStore)
            session_id: Unique session identifier
            config: Optional mode-specific configuration
        """
        self.store = store
        self.session_id = session_id
        self.config = config or {}
        self._loaded = False
        # Set by prepare_context(); consumed by update() for the human message
        self._pending_user_ts: str | None = None

        # ── Hybrid memory state ──────────────────────────────────────
        self._llm: Any = None  # set via set_llm()
        self._summary: str | None = None
        # How many messages (from the start) are covered by the summary.
        self._summary_msg_idx: int = 0

        # Optional vector recall (set via set_embeddings())
        self._vector_store: Any = None  # SessionVectorStore | None

    # ── Hybrid memory wiring ────────────────────────────────────────

    def set_llm(self, llm: Any) -> None:
        """Attach an LLM for summarization.

        Called from ``cogtrix.py`` after the LLM is created (and again
        whenever the user switches model/provider at runtime).
        """
        self._llm = llm

    def set_embeddings(self, embedding_fn: Any, embedding_model: str) -> None:
        """Attach an embedding function for vector recall.

        Creates (or reconfigures) a per-session ``SessionVectorStore``.
        Skipped when embedding is unavailable — vector recall simply
        won't contribute to context.
        """
        from src.memory.recall import SessionVectorStore

        if self._vector_store is None:
            self._vector_store = SessionVectorStore(self.session_id)
        self._vector_store.configure(embedding_fn, embedding_model)

    def _hybrid_meta_path(self) -> Path:
        """Return the path for the hybrid-state meta file.

        Derived from the store's base directory when available,
        otherwise falls back to ``data/history/``.
        """
        safe_id = self.session_id.replace("/", "_").replace("\\", "_")
        if len(safe_id) > 128:
            safe_id = safe_id[:128]
        base = getattr(self.store, "base_path", Path("data/history"))
        return base / f"{safe_id}_hybrid.json"

    def _save_hybrid_meta(self) -> None:
        """Persist summary state and vector store metadata to a file."""
        if self._summary is None and self._summary_msg_idx == 0:
            meta_path = self._hybrid_meta_path()
            if meta_path.exists():
                meta_path.unlink(missing_ok=True)
            return
        meta = {
            "_summary": self._summary,
            "_summary_msg_idx": self._summary_msg_idx,
        }
        try:
            meta_path = self._hybrid_meta_path()
            meta_path.parent.mkdir(parents=True, exist_ok=True)
            meta_path.write_text(json.dumps(meta, ensure_ascii=False), encoding="utf-8")
        except Exception as exc:
            log.warning("Failed to save hybrid meta: %s", exc)

    def _load_hybrid_meta(self) -> None:
        """Restore summary state from the meta file (if present)."""
        meta_path = self._hybrid_meta_path()
        if not meta_path.exists():
            return
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            self._summary = meta.get("_summary")
            self._summary_msg_idx = meta.get("_summary_msg_idx", 0)
        except Exception as exc:
            log.warning("Failed to load hybrid meta: %s", exc)

    def _clamp_summary_idx(self) -> None:
        """Ensure ``_summary_msg_idx`` does not exceed the message count.

        After ``sanitize_history()`` removes entries the stored index
        may point past the end of the (now shorter) message list.
        Clamping prevents messages from being skipped or re-summarized.
        """
        msg_count = self.get_message_count()
        if self._summary_msg_idx > msg_count:
            self._summary_msg_idx = msg_count

    def _maybe_summarize(self, messages: list[Any], window_size: int) -> None:
        """Summarize messages that have fallen outside the sliding window.

        Called from ``update()`` in each mode after new messages are
        appended.  This is a no-op when the LLM is not set, when the
        batch threshold has not been reached, or when summarization
        is disabled via config (``summarization: false``).
        """
        if not self._llm:
            return

        # Allow the config to disable summarization
        if not self.config.get("summarization", True):
            return

        total = len(messages)
        window_start = max(0, total - window_size)

        unsummarized_start = min(self._summary_msg_idx, total)
        unsummarized_end = window_start

        unsummarized_count = unsummarized_end - unsummarized_start
        if unsummarized_count < _SUMMARY_BATCH_SIZE:
            return

        batch = messages[unsummarized_start:unsummarized_end]

        from src.memory.summarizer import generate_summary

        new_summary = generate_summary(self._llm, batch, self._summary)
        if new_summary is not None:
            self._summary = new_summary
            self._summary_msg_idx = unsummarized_end
            log.debug(
                "Summary updated: covers messages 0..%d (%d tokens est.)",
                unsummarized_end,
                len(new_summary) // 4,
            )

            # Feed the newly summarised messages into vector recall.
            # Only done when the summary index advances to avoid
            # re-embedding the same batch on a summarization retry.
            if self._vector_store is not None:
                self._vector_store.add_messages(batch)

    def _build_hybrid_prefix(self, user_input: str) -> str | None:
        """Build the hybrid-memory portion of the context prefix.

        Returns a string containing the rolling summary and any
        vector-recalled past exchanges, or ``None`` if neither is
        available.
        """
        parts: list[str] = []

        if self._summary:
            parts.append(f"Conversation summary (older context):\n{self._summary}")

        # Vector recall
        if self._vector_store is not None and self._vector_store.ready:
            recall_k = self.config.get("vector_recall_k", 3)
            recalled = self._vector_store.recall(user_input, k=recall_k)
            if recalled:
                joined = "\n---\n".join(recalled)
                parts.append(f"Related past exchanges:\n{joined}")

        return "\n\n".join(parts) if parts else None

    # ── Abstract interface ───────────────────────────────────────────

    @property
    @abstractmethod
    def mode_name(self) -> str:
        """
        Return the mode identifier.

        Returns:
            Mode name string (e.g., 'conversation', 'code', 'reasoning')
        """
        pass

    @abstractmethod
    def prepare_context(self, user_input: str) -> MemoryContext:
        """
        Prepare context for the LLM given new user input.

        This method is called before each LLM invocation. It should:
        1. Select relevant messages from history
        2. Add any mode-specific context (summaries, entities, etc.)
        3. Return a MemoryContext with everything the LLM needs

        Args:
            user_input: The user's current input (for relevance filtering)

        Returns:
            MemoryContext with messages and metadata
        """
        pass

    @abstractmethod
    def update(
        self,
        user_input: str,
        ai_response: str,
        agent_messages: list[Any] | None = None,
    ) -> None:
        """
        Update memory after a conversation turn.

        Called after the LLM response is received. Should:
        1. Add new messages to history
        2. Extract any mode-specific information
        3. Trigger any necessary processing (summarization, etc.)

        Args:
            user_input: The user's input for this turn
            ai_response: The AI's response for this turn
            agent_messages: If provided, the *full* agent message chain
                for this turn (AIMessages with tool_calls, ToolMessages,
                and the final AIMessage).  Saving these enables the
                "Ralph Loop" — the agent can see its previous tool usage
                and continue iterating on complex tasks across restarts.
        """
        pass

    def get_system_prompt_additions(self) -> str | None:
        """
        Return mode-specific additions to the system prompt.

        Override this to add mode-specific instructions to the LLM.

        Returns:
            String to append to system prompt, or None
        """
        return None

    def load(self) -> None:
        """
        Load state from storage.

        Called once at session start. Override to load mode-specific state.
        Base implementation just marks as loaded.
        """
        self._loaded = True

    @staticmethod
    def _has_tool_calls(msg: Any) -> bool:
        """Return True if *msg* is an AI intermediate step with tool_calls."""
        tc = getattr(msg, "tool_calls", None) or (isinstance(msg, dict) and msg.get("tool_calls"))
        return bool(tc)

    @staticmethod
    def sanitize_history(messages: list[Any]) -> list[Any]:
        """
        Remove poisoned entries from conversation history.

        Filters out:
        - AI messages with empty content (but **not** intermediate
          tool-calling steps that legitimately have empty text)
        - AI messages containing error responses
        - Orphaned human messages (where the AI response was removed)

        ToolMessages and AIMessages with ``tool_calls`` (intermediate
        agent steps) are always preserved — they form the agent's
        working chain needed for iterative continuation (Ralph Loop).

        Args:
            messages: List of message dicts or BaseMessage objects

        Returns:
            Cleaned list of messages with invalid pairs removed
        """
        cleaned: list[Any] = []
        removed = 0
        i = 0

        while i < len(messages):
            msg = messages[i]

            # Get content and type from message
            if isinstance(msg, dict):
                content = _coerce_content(msg.get("content", ""))
                msg_type = msg.get("type", "")
            elif hasattr(msg, "content"):
                content = _coerce_content(msg.content)
                msg_type = type(msg).__name__.lower()
            else:
                cleaned.append(msg)
                i += 1
                continue

            # ToolMessages are intermediate agent steps — always keep.
            is_tool = msg_type in ("tool", "toolmessage")
            if is_tool:
                cleaned.append(msg)
                i += 1
                continue

            # AIMessages with tool_calls are intermediate steps — always keep.
            is_ai = msg_type in ("ai", "aimessage")
            if is_ai and BaseMemoryManager._has_tool_calls(msg):
                cleaned.append(msg)
                i += 1
                continue

            # Check if this is a human message followed by a bad AI response
            is_human = msg_type in ("human", "humanmessage")
            if is_human and i + 1 < len(messages):
                next_msg = messages[i + 1]
                if isinstance(next_msg, dict):
                    next_content = _coerce_content(next_msg.get("content", ""))
                    next_type = next_msg.get("type", "")
                elif hasattr(next_msg, "content"):
                    next_content = _coerce_content(next_msg.content)
                    next_type = type(next_msg).__name__.lower()
                else:
                    next_content = ""
                    next_type = ""

                next_is_ai = next_type in ("ai", "aimessage")
                # Only treat as "bad pair" when next message is a plain
                # AI response (no tool_calls) with error content.
                if (
                    next_is_ai
                    and not BaseMemoryManager._has_tool_calls(next_msg)
                    and _is_bad_ai_content(next_content)
                ):
                    removed += 2
                    i += 2
                    continue

            # Check standalone AI message with bad content
            if is_ai and _is_bad_ai_content(content):
                removed += 1
                i += 1
                continue

            cleaned.append(msg)
            i += 1

        if removed > 0:
            log.info(
                f"History sanitized: removed {removed} poisoned entries "
                f"({len(messages)} -> {len(cleaned)} messages)"
            )

        return cleaned

    # ── Timestamp utilities ─────────────────────────────────────────

    @staticmethod
    def _now_ts() -> str:
        """Return the current UTC time as an ISO 8601 string with 'Z' suffix."""
        return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

    @staticmethod
    def _get_msg_ts(msg: Any) -> str | None:
        """Extract the Cogtrix ``_ts`` timestamp from a message, if any."""
        if hasattr(msg, "additional_kwargs"):
            return (msg.additional_kwargs or {}).get("_ts")
        if isinstance(msg, dict):
            return msg.get("timestamp")
        return None

    @staticmethod
    def _set_msg_ts(msg: Any, ts: str | None = None) -> None:
        """Attach a timestamp to *msg* in-place."""
        if ts is None:
            ts = BaseMemoryManager._now_ts()
        if hasattr(msg, "additional_kwargs"):
            if msg.additional_kwargs is None:
                msg.additional_kwargs = {}
            msg.additional_kwargs["_ts"] = ts
        elif isinstance(msg, dict):
            msg["timestamp"] = ts

    @staticmethod
    def _inject_timestamps(messages: list[Any]) -> list[Any]:
        """Return copies of *messages* with ``[YYYY-MM-DD HH:MM:SS UTC]`` prepended.

        Messages that have no stored timestamp are returned as-is.
        ToolMessages and AIMessages that are intermediate tool-calling
        steps (have ``tool_calls`` but no meaningful text) are passed
        through unchanged — timestamps are only displayed on the
        "bookend" Human/AI messages.  The originals are never mutated.
        """

        def _str_content(m: Any) -> str:
            c = m.content if hasattr(m, "content") else m.get("content", "")
            return c if isinstance(c, str) else str(c) if c else ""

        result: list[Any] = []
        for msg in messages:
            # Determine type name
            if isinstance(msg, dict):
                mt = msg.get("type", "")
            else:
                mt = type(msg).__name__.lower()

            # ToolMessages: pass through unchanged (no timestamp prefix)
            if mt in ("tool", "toolmessage"):
                result.append(msg)
                continue

            # Intermediate AI steps (tool_calls, empty/minimal text): keep as-is
            if mt in ("ai", "aimessage") and BaseMemoryManager._has_tool_calls(msg):
                result.append(msg)
                continue

            # No timestamp stored → keep as-is
            ts = BaseMemoryManager._get_msg_ts(msg)
            if not ts:
                result.append(msg)
                continue

            # Build compact display string (with seconds, marked UTC)
            try:
                raw = ts.rstrip("Z")
                dt = datetime.fromisoformat(raw)
                display = dt.strftime("%Y-%m-%d %H:%M:%S") + " UTC"
            except (ValueError, TypeError):
                display = ts

            prefix = f"[{display}] "

            if HumanMessage is not None and isinstance(msg, HumanMessage):
                result.append(HumanMessage(content=prefix + _str_content(msg)))
            elif AIMessage is not None and isinstance(msg, AIMessage):
                result.append(AIMessage(content=prefix + _str_content(msg)))
            elif isinstance(msg, dict) and "content" in msg:
                result.append({**msg, "content": prefix + _str_content(msg)})
            else:
                result.append(msg)
        return result

    # ── Persistence hooks ────────────────────────────────────────

    def save(self) -> None:  # noqa: B027
        """
        Persist current state to storage.

        Called after each turn. Override to save mode-specific state.
        Subclasses should call ``super().save()`` to persist vector store
        and hybrid summary meta.
        """
        self._save_hybrid_meta()
        if self._vector_store is not None:
            self._vector_store.save()

    def clear(self) -> None:  # noqa: B027
        """
        Clear all memory for this session.

        Resets to initial state. Override to clear mode-specific data.
        Default is a no-op (subclasses should call super().clear()).
        """
        self._summary = None
        self._summary_msg_idx = 0
        if self._vector_store is not None:
            self._vector_store.clear()
        # Remove persisted meta file
        try:
            meta_path = self._hybrid_meta_path()
            if meta_path.exists():
                meta_path.unlink(missing_ok=True)
        except Exception:
            pass

    def get_stats(self) -> dict[str, Any]:
        """
        Return statistics about current memory state.

        Useful for debugging and display.

        Returns:
            Dictionary with mode-specific statistics
        """
        return {
            "mode": self.mode_name,
            "session_id": self.session_id,
            "loaded": self._loaded,
        }

    def get_message_count(self) -> int:
        """
        Return the total number of messages stored.

        Override in subclasses that track messages.

        Returns:
            Number of messages in memory
        """
        return 0

    @staticmethod
    def _estimate_tokens(messages: list[Any]) -> int:
        """Rough token estimation for a list of messages.

        Uses simple heuristic: ~4 characters per token.
        Handles both string and list (multimodal) content.

        Args:
            messages: List of messages

        Returns:
            Estimated token count
        """
        total_chars = 0
        for msg in messages:
            if hasattr(msg, "content") and msg.content:
                total_chars += len(_coerce_content(msg.content))
            elif isinstance(msg, dict) and msg.get("content"):
                total_chars += len(_coerce_content(msg["content"]))
        return total_chars // 4

    # --- Serialization interface (for persistence) ---

    def to_dict(self) -> dict[str, Any]:
        """
        Serialize full state to dictionary.

        Override to include mode-specific state.

        Returns:
            Dictionary representation of state
        """
        d: dict[str, Any] = {
            "mode": self.mode_name,
            "version": 1,
            "session_id": self.session_id,
            "config": self.config,
        }
        # Hybrid state
        if self._summary is not None:
            d["_summary"] = self._summary
            d["_summary_msg_idx"] = self._summary_msg_idx
        return d

    def from_dict(self, data: dict[str, Any]) -> None:
        """
        Restore state from dictionary.

        Override to restore mode-specific state.
        Only restores serialized config if no runtime config was provided
        during __init__, so that live/reloaded config is not overwritten.

        Args:
            data: Dictionary from to_dict()

        Raises:
            ValueError: If mode in data doesn't match this manager's mode
        """
        if data.get("mode") != self.mode_name:
            raise ValueError(f"Mode mismatch: expected {self.mode_name}, got {data.get('mode')}")
        # Only apply serialized config when no runtime config was set
        if not self.config:
            self.config = data.get("config", {})

        # Restore hybrid state
        self._summary = data.get("_summary")
        self._summary_msg_idx = data.get("_summary_msg_idx", 0)
