"""
Abstract base class for memory management strategies.
All memory modes must inherit from this class.
"""

import logging
from abc import ABC, abstractmethod
from typing import Any

from src.memory.base import BaseMemoryStore
from src.memory.context import MemoryContext

log = logging.getLogger("cogtrix")

# Error prefixes that should never be stored in conversation history.
# These are generated by _format_agent_error() in cogtrix.py.
_ERROR_PREFIXES = (
    "**Model not found:**",
    "**Authentication failed:**",
    "**Rate limit exceeded.**",
    "**Connection error:**",
    "**Request timed out.**",
    "**Invalid request:**",
    "**API server error",
    "**Service temporarily unavailable",
    "**Error:**",
    "**Agent iteration limit reached.**",
    "**Partial results",
)


def _is_bad_ai_content(content: str) -> bool:
    """Check if AI message content is empty or an error message."""
    if not content or not content.strip():
        return True
    stripped = content.strip()
    for prefix in _ERROR_PREFIXES:
        if stripped.startswith(prefix):
            return True
    return False


class BaseMemoryManager(ABC):
    """
    Abstract interface for memory management strategies.

    Each memory mode (conversation, code, reasoning) implements this
    interface to provide mode-specific context preparation and updates.

    Lifecycle:
        1. __init__() - Create manager with store and session
        2. load() - Load existing state from storage
        3. prepare_context() - Get context for LLM (called before each turn)
        4. update() - Update memory after LLM response
        5. save() - Persist state to storage

    Attributes:
        store: Storage backend for persistence
        session_id: Unique identifier for this session
        config: Mode-specific configuration options
    """

    def __init__(
        self,
        store: BaseMemoryStore,
        session_id: str,
        config: dict[str, Any] | None = None,
    ):
        """
        Initialize the memory manager.

        Args:
            store: Storage backend (e.g., JsonFileMemoryStore)
            session_id: Unique session identifier
            config: Optional mode-specific configuration
        """
        self.store = store
        self.session_id = session_id
        self.config = config or {}
        self._loaded = False

    @property
    @abstractmethod
    def mode_name(self) -> str:
        """
        Return the mode identifier.

        Returns:
            Mode name string (e.g., 'conversation', 'code', 'reasoning')
        """
        pass

    @abstractmethod
    def prepare_context(self, user_input: str) -> MemoryContext:
        """
        Prepare context for the LLM given new user input.

        This method is called before each LLM invocation. It should:
        1. Select relevant messages from history
        2. Add any mode-specific context (summaries, entities, etc.)
        3. Return a MemoryContext with everything the LLM needs

        Args:
            user_input: The user's current input (for relevance filtering)

        Returns:
            MemoryContext with messages and metadata
        """
        pass

    @abstractmethod
    def update(self, user_input: str, ai_response: str) -> None:
        """
        Update memory after a conversation turn.

        Called after the LLM response is received. Should:
        1. Add new messages to history
        2. Extract any mode-specific information
        3. Trigger any necessary processing (summarization, etc.)

        Args:
            user_input: The user's input for this turn
            ai_response: The AI's response for this turn
        """
        pass

    def get_system_prompt_additions(self) -> str | None:
        """
        Return mode-specific additions to the system prompt.

        Override this to add mode-specific instructions to the LLM.

        Returns:
            String to append to system prompt, or None
        """
        return None

    def load(self) -> None:
        """
        Load state from storage.

        Called once at session start. Override to load mode-specific state.
        Base implementation just marks as loaded.
        """
        self._loaded = True

    @staticmethod
    def sanitize_history(messages: list[Any]) -> list[Any]:
        """
        Remove poisoned entries from conversation history.

        Filters out:
        - AI messages with empty content
        - AI messages containing error responses
        - Orphaned human messages (where the AI response was removed)

        This prevents the LLM from being influenced by error patterns
        in the history, which can cause it to return empty responses.

        Args:
            messages: List of message dicts or BaseMessage objects

        Returns:
            Cleaned list of messages with invalid pairs removed
        """
        cleaned: list[Any] = []
        removed = 0
        i = 0

        while i < len(messages):
            msg = messages[i]

            # Get content and type from message
            if isinstance(msg, dict):
                content = msg.get("content", "")
                msg_type = msg.get("type", "")
            elif hasattr(msg, "content"):
                content = msg.content or ""
                msg_type = type(msg).__name__.lower()
            else:
                cleaned.append(msg)
                i += 1
                continue

            # Check if this is a human message followed by a bad AI response
            is_human = msg_type in ("human", "humanmessage")
            if is_human and i + 1 < len(messages):
                next_msg = messages[i + 1]
                if isinstance(next_msg, dict):
                    next_content = next_msg.get("content", "")
                    next_type = next_msg.get("type", "")
                elif hasattr(next_msg, "content"):
                    next_content = next_msg.content or ""
                    next_type = type(next_msg).__name__.lower()
                else:
                    next_content = ""
                    next_type = ""

                is_ai = next_type in ("ai", "aimessage")
                if is_ai and _is_bad_ai_content(next_content):
                    # Skip both the human message and the bad AI response
                    removed += 2
                    i += 2
                    continue

            # Check standalone AI message with bad content
            is_ai = msg_type in ("ai", "aimessage")
            if is_ai and _is_bad_ai_content(content):
                removed += 1
                i += 1
                continue

            cleaned.append(msg)
            i += 1

        if removed > 0:
            log.info(
                f"History sanitized: removed {removed} poisoned entries "
                f"({len(messages)} -> {len(cleaned)} messages)"
            )

        return cleaned

    def save(self) -> None:  # noqa: B027
        """
        Persist current state to storage.

        Called after each turn. Override to save mode-specific state.
        Default is a no-op.
        """

    def clear(self) -> None:  # noqa: B027
        """
        Clear all memory for this session.

        Resets to initial state. Override to clear mode-specific data.
        Default is a no-op.
        """

    def get_stats(self) -> dict[str, Any]:
        """
        Return statistics about current memory state.

        Useful for debugging and display.

        Returns:
            Dictionary with mode-specific statistics
        """
        return {
            "mode": self.mode_name,
            "session_id": self.session_id,
            "loaded": self._loaded,
        }

    def get_message_count(self) -> int:
        """
        Return the total number of messages stored.

        Override in subclasses that track messages.

        Returns:
            Number of messages in memory
        """
        return 0

    # --- Serialization interface (for persistence) ---

    def to_dict(self) -> dict[str, Any]:
        """
        Serialize full state to dictionary.

        Override to include mode-specific state.

        Returns:
            Dictionary representation of state
        """
        return {
            "mode": self.mode_name,
            "version": 1,
            "session_id": self.session_id,
            "config": self.config,
        }

    def from_dict(self, data: dict[str, Any]) -> None:
        """
        Restore state from dictionary.

        Override to restore mode-specific state.
        Only restores serialized config if no runtime config was provided
        during __init__, so that live/reloaded config is not overwritten.

        Args:
            data: Dictionary from to_dict()

        Raises:
            ValueError: If mode in data doesn't match this manager's mode
        """
        if data.get("mode") != self.mode_name:
            raise ValueError(
                f"Mode mismatch: expected {self.mode_name}, " f"got {data.get('mode')}"
            )
        # Only apply serialized config when no runtime config was set
        if not self.config:
            self.config = data.get("config", {})
