"""Shared message validation utilities.

Error classification and content validation helpers used by both the
memory layer and the orchestration layer. Keeping them in one place
avoids cross-layer coupling and makes the prefix list a single source
of truth.
"""

from typing import Any

# Error prefixes that should never be stored in conversation history.
# These are generated by _format_agent_error() in cogtrix.py.
_ERROR_PREFIXES = (
    "**Model not found:**",
    "**Authentication failed:**",
    "**Rate limit exceeded.**",
    "**Connection error:**",
    "**Request timed out.**",
    "**Prompt too long",
    "**Invalid request:**",
    "**API server error",
    "**Service temporarily unavailable",
    "**Error:**",
    "**Agent iteration limit reached.**",
    "**Partial results",
    "An error occurred: ",
    "**Cannot connect to Ollama.**",
    "**Ollama model not found.**",
)


def _coerce_content(content: Any) -> str:
    """Safely coerce message content to a plain string.

    LangChain messages may carry ``content`` as a ``str``, a ``list``
    (multimodal messages), or occasionally ``None``.  This helper
    normalises all variants to a flat string so downstream code can
    safely call ``.strip()`` etc.
    """
    if isinstance(content, str):
        return content
    if content is None:
        return ""
    if isinstance(content, list):
        parts: list[str] = []
        for item in content:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict):
                parts.append(item.get("text", str(item)))
            else:
                parts.append(str(item))
        return " ".join(parts)
    return str(content)


def is_bad_ai_content(content: Any) -> bool:
    """Check if AI message content is empty or an error message.

    Accepts any content type (str, list, None) and coerces to string
    before checking.
    """
    text = _coerce_content(content)
    if not text or not text.strip():
        return True
    stripped = text.strip()
    for prefix in _ERROR_PREFIXES:
        if stripped.startswith(prefix):
            return True
    return False
