{{- if .Values.externalSecrets.enabled }}
{{- $secretName := .Values.externalSecrets.target.name | default (include "cogtrix.fullname" .) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name | default (include "cogtrix.fullname" .) }}
  labels:
    {{- include "cogtrix.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "SecretStore" }}
  target:
    name: {{ $secretName }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.data | nindent 4 }}
{{- end }}
